import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Login from '@/components/Login'


export default function Home() {
  return (
    <>
      <Head>
        <title>Login - Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/instafavicon.png" />
      </Head>
      <main className={`${styles.main}`}>
        <Login/>
      </main>
    </>
  )
}
